### ISSUE TITLE
There's not an appropriate way to Pause/Resume a job

### ISSUE THREAD

**Issue by joint-song** [reugn/go-quartz#100]
Quartz-Java supports Pausing/Resuming a job(Scheduler class in [Quartz JavaDoc](https://www.quartz-scheduler.org/api/2.3.0/index.html)). Will go-quartz support this?
And I can implement this by a pausing flag in my queue DB table temporarily, but this may result in some race conflicts with go-quartz scheduler's routines.

**Comment by reugn** [comment]
PR #102 adds the `PauseJob` and `ResumeJob` methods to the `Scheduler` interface. A breaking change was introduced to the `JobQueue` interface by adding the Get method in #101. Let me know if this works for you.

**Comment by joint-song** [comment]
This PR resolved my problem, that's great!
