### ISSUE TITLE
Some cron-expression will fail to be parsed.

### ISSUE THREAD

**Issue by joint-song** [reugn/go-quartz#114]
Cron expression like `04 28 7-23/4 * * ?` cannot be parsed. Java-Quartz works fine, which conforms to the same with [crontab guru](https://crontab.guru/#04_7-23/4_*_*_*).

**Comment by reugn** [comment]
PR #115 resolved the issue with the given example and other compound  field cases in the cron expression. Please let me know if you encounter any other cron expression parsing errors.

**Comment by fighterhit** [comment]
Hi @reugn , I also found the[ complex expression](https://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html#:~:text=or%20more%20complex%2C%20like%20this%3A%200/5%2014%2C18%2C3%2D39%2C52%20*%20%3F%20JAN%2CMAR%2CSEP%20MON%2DFRI%202002%2D2010) on the quartz official documentation could not be parsed correctly.
```
 0/5 14,18,3-39,52 * ? JAN,MAR,SEP MON-FRI 2002-2010
```
