### ISSUE TITLE
How to get job context info in NewFunctionJob callback ?

### ISSUE THREAD

**Issue by zhangjie2012** [reugn/go-quartz#135]
e.g:

``` go
functionJob := job.NewFunctionJob(func(ctx context.Context) (int, error) {
  // get which job id tiggered in here
  return 42, nil
})
```

in fact, I want add more job params to callback.

**Comment by reugn** [comment]
@zhangjie2012, it makes sense to me to add the `JobKey` details of the job to the context, but may I ask the reason you need it? `JobDetailOptions` also can be made available. What other information would you expect to be accessible within the context?

**Comment by zhangjie2012** [comment]
Finally, I solved it using this way：
``` go
callbackJob := job.NewFunctionJob(func(_ context.Context) (n int, err error) {
	ctx := CronJobCtx{
		// cronjob runtime info, like name/id/params
	}
	err = handleCronJob(&ctx)
	return
})
```

**Comment by zhangjie2012** [comment]
package gocron's implementation is elegant. like:
```
gocron.NewTask(
	func(a string, b int) {
			// do things
		},
		"hello",
		1,
	),
)
```

a common requirement is to inject some runtime parameters to my callback function.
