### ISSUE TITLE
Persistent Job store

### ISSUE THREAD

**Issue by gedw99** [reugn/go-quartz#17]
Is there a storage layer for this ?

I was thinking of adding a JSON based storage and some sort of  web based gui to configure that json.

essentially it’s really a config .

then there is the question of if the config is changed via the Jain , how we update the running program without restarting .

what do you think ? 

Do you have other plans for this area perhaps ?

**Comment by reugn** [comment]
I don't think I understand the question. If you're asking about a persistent Job store, there is none yet. I would think about an interface and various DB implementations.

**Comment by gedw99** [comment]
Yes that’s what I was asking about.

Sorry if I did not make that clear.

you may want to consider Ent but as you know there are a myriad of options :)

https://github.com/ent/ent

**Comment by dolmen** [comment]
Exporting the job list is already possible.

A job store should _not_ be bundled in _this_ package to limit dependencies.

**Comment by gedw99** [comment]
> Exporting the job list is already possible.
> 
> A job store should _not_ be bundled in _this_ package to limit dependencies.

OK good to know.
