### ISSUE TITLE
How to disable logging "The Job '*' got out the execution loop"?

### ISSUE THREAD

**Issue by kusurov** [reugn/go-quartz#21]
Hi! 

After running trigger RunOnceTrigger is always written to logs: "The Job '*' got out the execution loop". Can I turn this off?

**Comment by reugn** [comment]
@kusurov, you can turn logs off using
```go
func init() {
    log.SetOutput(ioutil.Discard)
}
```

**Comment by morawskim** [comment]
Hello,

I use this library in project where we use also `slog` library with JSON handler and I am also affected with this issue.
I have created patch (https://github.com/reugn/go-quartz/compare/master...morawskim:go-quartz:logger). 

@reugn  If you are interested in this solution, I can prepare PR and adjust code.

At the moment there are two potential issues in my fork:
* the API has changed. I have added second argument to `NewStdSchedulerWithOptions`. I could add this as another field in `StdSchedulerOptions`. What do you think?
* the Interface requires only one method `Log`. At the moment it looks like is enought and we don't need more (Debug, Info, Warning etc)

**Comment by reugn** [comment]
A logger interface has been added in #67.
