### ISSUE TITLE
No Restriction on Jobs with Same Key

### ISSUE THREAD

**Issue by Hoteliar** [reugn/go-quartz#22]
Tried to insert 2 jobs with same key (int), both of them were inserted. But the GetScheduledJob by ID only returns one job.
I expect the second will override the first one.

**Comment by pires** [comment]
IIUC the same problem happens if you delete by ID, where only the first Job found w/ said ID is deleted but others stay scheduled. That said, I'm currently thinking ensuring only one job with a certain ID is present by always overwriting seems like the sane thing to do.

**Comment by reugn** [comment]
The original Java Quartz throws an exception on a duplicate job being scheduled. The current architecture would require a full scan of all scheduled jobs to detect duplicates, which is inefficient. It's possible to explicitly call the `DeleteJob` before scheduling a job to check for uniqueness. But this requires the user to be aware of the possible problem with duplicating jobs.

**Comment by pires** [comment]
Could `DeleteJob` return the deleted instance? This way one could:
```golang
job := DeleteJob(id)
for job != nil {
    job = DeleteJob(id)
}
// no jobs w/ ID
```

If this doesn't look crazy, it could even be added as an helper to this lib, eg `ClearJob(id)`?

**Comment by reugn** [comment]
Yes, this one would work, but it's odd and wrong to have this functionality hidden from the user. In the meantime, the only error returned is the "No Job found" which could be an indicator. I would keep this open to wait for proper refactoring to handle the job duplication issue.

**Comment by pires** [comment]
Maybe a _stop-gap_ solution could be to comment the function definitions to warn about this and maybe point to this issue as a TODO?
