### ISSUE TITLE
add support for contexts in scheduler

### ISSUE THREAD

**Issue by tychoish** [reugn/go-quartz#40]
It would be nice to be able to have a context that is canceled when the job finishes executing to make it difficult/impossible for jobs to spawn go routines that last longer than the job execution itself. This change would also allow quartz schedulers to integrate with existing process/task lifescale mechanisms that use contexts.

I've prototyped this in this branch: https://github.com/tychoish/go-quartz/tree/dev-contexts.

If this is something that you/the project is interested in, I would be willing to carry this over the line.

**Comment by reugn** [comment]
Yes, @tychoish, that would be a valuable addition. Please open a PR.

**Comment by tychoish** [comment]
Cool, on its way!
