### ISSUE TITLE
invalid cron expression: fillRange

### ISSUE THREAD

**Issue by zhujintao** [reugn/go-quartz#49]
58 0/50 9-2 * * ? invalid cron expression: fillRange

**Comment by reugn** [comment]
@zhujintao, did you mean to use `58 0/50 2-9 * * ?` ?

**Comment by zhujintao** [comment]
> @zhujintao, did you mean to use `58 0/50 2-9 * * ?` ?
no, ```9-2``` skips the range of 3-8


util.go
```
func fillRange(from, to int, s ...int) ([]int, error) {

	if to < from {
		min, max := s[0], s[1]
		var arr []int
		for i := min; i <= max; i = i + 1 {
			if i <= to || i >= from {
				arr = append(arr, i)
			}
		}
		return arr, nil
	}
```

**Comment by zhujintao** [comment]
58 0/50 9-2 * * ? is  [Quartz ](https://github.com/quartz-scheduler/quartz)  cron expression, supported.

**Comment by reugn** [comment]
`58 0/50 0-2,9-23 * * ?` can be used with v0.8.0.
