### ISSUE TITLE
Cannot use alternative Logger implementations

### ISSUE THREAD

**Issue by tliron** [reugn/go-quartz#74]
From the code in [default_logger.go](https://github.com/reugn/go-quartz/blob/master/quartz/logger/default_logger.go) it seems you had a good intention to allow users to replace the default logger with their own implementation of the `Logger` interface. However, doing so will panic with:
```
sync/atomic: store of inconsistently typed value into Value
```
The reason is that `atomic.Value` doesn't work quite like you seem to think (I agree it's not entirely intuitive). From the documentation of `Value.Store`:
```
// Store sets the value of the Value v to val.
// All calls to Store for a given Value must use values of the same concrete type.
// Store of an inconsistent type panics, as does Store(nil).
```
What this means is that once you set the value to an instance of `SimpleLogger` in your `init()` function, the value will *only* accept `SimpleLogger` instances. This means that in my case I cannot install my own implementation of the `Logger` interface.

How to fix this? I would suggest using a simple `Logger` var instead of `atomic.Value`. This does mean no thread safety, but is it really necessary here? Users usually set up logging when they start the application and don't change it later. Most logging libraries are not thread safe in this way.

If you do want to insist on thread safety (perhaps to ensure behavior doesn't change for users who expect it) I would suggest wrapping access to the var in a simple mutex.

I'd be happy to submit a PR for either of these solutions, just let me know. Thanks for a very useful library!

**Comment by reugn** [comment]
@tliron, thanks for pointing that out. I switched to a synchronized approach to set the Logger (#75). An unprotected variable would be good in most cases, but why having the Data Race Detector upset. Let me know if this works for you.

**Comment by tliron** [comment]
Thank @reugn , it will indeed solve the issue. I made 2 comments on the PR, but they really aren't important.

**Comment by reugn** [comment]
Can't find any review on the PR.

**Comment by tliron** [comment]
Oops, forgot to click submit. You should get it now.
