### ISSUE TITLE
Is this distributed

### ISSUE THREAD

**Issue by zxpdmw** [reugn/go-quartz#79]
Excuse me, the implementation of this library distributed scheduling is distributed?

**Comment by prologic** [comment]
I don't think so

**Comment by reugn** [comment]
@zxpdmw, I've opened a pull request (https://github.com/reugn/go-quartz/pull/80) to support custom job queue implementation that can provide persistent storage and state sharing for jobs. Please review, and let me know if this satisfies your requirement.

**Comment by reugn** [comment]
Closed due to inactivity.
