### ISSUE TITLE
DeleteJob issue, when deleting job already waiting for execution

### ISSUE THREAD

**Issue by CmdPirx** [reugn/go-quartz#81]
H,

first of all: thanks for this library, it is great.

One remark regarding DeleteJob function:

DeleteJob removes a job from the queue, but doesn't cancel its execution, when it was the most recent job and it is already waiting for the timer event in the execution loop.
In this situation, after DeleteJob, the timer, set in startExecutionLoop is stil active and fires at calculated time (defined for in the meantime deleted job), and executes next current most recent job at wrong time.

In the example below:
1. Two jobs are defined ("First job" with 15s interval and  "Second job" with 30s interval)
2. "First job" is most recent and starts timer in startExecutionLoop, which will be fired after ca. 15s
3. After 5s, before timer fires, job "First job" will be deleted.
4. Because DeleteJob doesn't do reset(), timer is still active and fires calling executeAndReschedule()
5. executeAndReschedule gets most recent item from the heap (heap.Pop(sched.queue).(*item)), which is now "Second job" and executes it.
6. In this case, the calculation in (st *SimpleTrigger) NextFireTime() is also wrong: it adds the value of interval to the calculated previous start time (priority). However, it should use now() instead.

Example, based on sample code:
func sampleScheduler(ctx context.Context, wg *sync.WaitGroup) {
	defer wg.Done()

	sched := quartz.NewStdScheduler()

	sched.Start(ctx)

	_ = sched.ScheduleJob(ctx, &PrintJob{"First job"}, quartz.NewSimpleTrigger(time.Second*15))
	_ = sched.ScheduleJob(ctx, &PrintJob{"Second job"}, quartz.NewSimpleTrigger(time.Second*30))

	var wg1 sync.WaitGroup
	wg1.Add(1)
	go func() {
		defer wg1.Done()
		time.Sleep(time.Second * 5)
		fmt.Printf("delete job %d\n", quartz.HashCode("First job"))
		err := sched.DeleteJob(quartz.HashCode("First job"))
		if err != nil {
			fmt.Println(err)
			return
		}
		fmt.Println("Job deleted")
		jobs := sched.GetJobKeys()
		for i, j := range jobs {
			fmt.Printf("%d job %d\n", i, j)
		}

	}()

	wg1.Wait()
	
	jobs := sched.GetJobKeys()
	for i, j := range jobs {
		fmt.Printf("%d job %d\n", i, j)
	}

	wg1.Add(1)
	go func() {
		defer wg1.Done()
		fmt.Println("waiting 30 seconds...")
		time.Sleep(time.Second * 30)
	}()

	wg1.Wait()
	fmt.Println("Stopping...")
	sched.Stop()
	sched.Wait(ctx)
}

Solution:
 Call reset() in the DeleteJob function. However, sched.reset(ctx) requires context, which is not available in the DeleteJob
IMHO, this solution works properly:

func (sched *StdScheduler) DeleteJob2(ctx context.Context, key int) error {
	sched.mtx.Lock()
	defer sched.mtx.Unlock()

	for i, item := range *sched.queue {
		if item.Job.Key() == key {
			sched.queue.Remove(i)
			sched.reset(ctx)
			return nil
		}
	}

	return errors.New("no Job with the given Key found")
}

**Comment by reugn** [comment]
@CmdPirx, the fix introduces a breaking change by requiring a Context in `DeleteJob`.
