### ISSUE TITLE
How can I identify a Job from JobKey?

### ISSUE THREAD

**Issue by joint-song** [reugn/go-quartz#92]
There's not any method giving name of JobKey. So I'm not able to implement `JobQueue.Remove(JobKey)` and `JobQueue.Push(ScheduledJob)` methods for customizing a persistent JobQueue.
And another question: I think a persistent `JobQueue` based on widely used database example is really required. I'm using JobQueue in production, but I'm not very certain how implement this properly. Thanks.

**Comment by reugn** [comment]
@joint-song, you can identify the `JobDetail` by a `JobKey` and fetch the `Job` from it. It might help seeing the code if you have your work open-sourced. I will look into creating a sample implementation for reference, but it may take some time. The API changes hasn't been released yet, and any improvement suggestions  would be appreciated.

**Comment by reugn** [comment]
[v0.10.0](https://github.com/reugn/go-quartz/releases/tag/v0.10.0) has been released. You can find an example implementation of the job queue using the file system as the persistence layer [here](https://github.com/reugn/go-quartz/blob/v0.10.0/examples/queue/file_system.go).

**Comment by joint-song** [comment]
Thanks for your help. Have a nice day!
